# Generated by Django 5.0.6 on 2024-08-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staff_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
