# Generated by Django 5.0.1 on 2024-06-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number2",
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
