# Generated by Django 5.0.6 on 2024-08-09 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0002_staff_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Electrician",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.IntegerField(db_index=True, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "temporary_address_line",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.DateField(blank=True, default=None, null=True)),
                ("national_id", models.CharField(blank=True, max_length=20, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("health_conditions", models.TextField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("spouse_name", models.CharField(blank=True, max_length=50, null=True)),
                ("spouse_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "spouse_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                ("mother_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("certifications", models.TextField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("previous_employers", models.TextField(blank=True, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                (
                    "nominee_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nominee_relation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nominee_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "nominee_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "nominee_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("child1_name", models.CharField(blank=True, max_length=50, null=True)),
                ("child1_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "child1_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "child1_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("child2_name", models.CharField(blank=True, max_length=50, null=True)),
                ("child2_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "child2_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "child2_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("child3_name", models.CharField(blank=True, max_length=50, null=True)),
                ("child3_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "child3_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "child3_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("child4_name", models.CharField(blank=True, max_length=50, null=True)),
                ("child4_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "child4_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "child4_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("child5_name", models.CharField(blank=True, max_length=50, null=True)),
                ("child5_dob", models.DateField(blank=True, default=None, null=True)),
                (
                    "child5_gender",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "child5_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electrician_district",
                        to="staff.district",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
