# Generated by Django 5.0.6 on 2024-08-10 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0003_delete_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.IntegerField(db_index=True, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "client_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("end_user", "End User"),
                            ("business_client", "Business Client"),
                            ("government", "Government"),
                            ("non_profit", "Non-Profit"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=50, null=True)),
                ("industry", models.CharField(blank=True, max_length=50, null=True)),
                ("followup_date", models.DateField(blank=True, null=True)),
                ("followup_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="client_photos/"
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_assigned_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_district_name",
                        to="staff.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
