# Generated by Django 5.0.6 on 2024-08-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("staff", "0003_delete_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_assigned_staff",
                to="staff.staff",
            ),
        ),
    ]
