# Generated by Django 5.0.6 on 2024-07-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmansalestargetstatus",
            name="sales_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_target",
                to="task.saletarget",
            ),
        ),
    ]
