# Generated by Django 5.0.1 on 2024-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saletarget",
            name="avg_transaction_value_target",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saletarget",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saletarget",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="saletarget",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="saletarget",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="saletarget",
            name="sales_target_revenue",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saletarget",
            name="target_period",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="saletarget",
            name="units_sold_target",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
