# Generated by Django 5.0.6 on 2024-08-07 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staff_profile_picture"),
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.IntegerField(db_index=True, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("heading", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("location_place_name", models.CharField(max_length=255)),
                ("delivery_date", models.DateTimeField()),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("DELIVERY", "Delivery"), ("RETURN", "Return")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivered_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_staff",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
