# Generated by Django 5.0.6 on 2024-07-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_salesmansalestargetstatus_sales_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftask",
            name="contact_file",
            field=models.FileField(blank=True, null=True, upload_to="task_contacts/"),
        ),
        migrations.AddField(
            model_name="stafftask",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="task_documents/"),
        ),
        migrations.AlterField(
            model_name="salesmansalestargetstatus",
            name="sales_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_target_status",
                to="task.saletarget",
            ),
        ),
    ]
