# Generated by Django 5.0.1 on 2024-07-04 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_saletarget_avg_transaction_value_target_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesmansalestargetstatus",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="salesmansalestargetstatus",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
