# Generated by Django 5.0.1 on 2024-07-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_remove_salesmansalestargetstatus_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmansalestargetstatus",
            name="sales_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_statuses",
                to="task.saletarget",
            ),
        ),
    ]
