# Generated by Django 5.0.6 on 2024-08-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_delivery_customer_address_delivery_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesmancustomerrelationshiptargetstatus",
            name="progress_customer_satisfaction_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="salesmansalestargetstatus",
            name="progress_sale_revenue",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
