# Generated by Django 5.0.6 on 2024-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_companynotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companynotes",
            name="note_title",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
