# Generated by Django 5.0.6 on 2024-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task",
            "0004_salesmancustomerrelationshiptargetstatus_progress_customer_satisfaction_score_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="location",
        ),
        migrations.AddField(
            model_name="delivery",
            name="call_report_followup",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_google_map_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("CHECK", "Check"), ("UPI", "UPI")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="pending_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
