# Generated by Django 5.0.1 on 2024-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_remove_customerrelationshiptarget_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftask",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="task_audio/"),
        ),
        migrations.AddField(
            model_name="stafftask",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="task_images/"),
        ),
    ]
