# Generated by Django 5.0.6 on 2024-07-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("task", "0005_alter_companynotes_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrelationshiptarget",
            name="salesman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_relationship_targets",
                to="staff.staff",
            ),
        ),
        migrations.AlterField(
            model_name="saletarget",
            name="salesman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sal_targets",
                to="staff.staff",
            ),
        ),
        migrations.AlterField(
            model_name="stafftask",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_tasks",
                to="staff.staff",
            ),
        ),
    ]
