# Generated by Django 5.0.6 on 2024-07-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("task", "0006_alter_customerrelationshiptarget_salesman_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forwarded_at", models.DateTimeField()),
                (
                    "new_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_tasks",
                        to="staff.staff",
                    ),
                ),
                (
                    "previous_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_tasks",
                        to="staff.staff",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_histories",
                        to="task.stafftask",
                    ),
                ),
            ],
        ),
    ]
