# Generated by Django 5.0.6 on 2024-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_taskhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companynotes",
            options={
                "verbose_name": "Company Note",
                "verbose_name_plural": "Company Notes",
            },
        ),
        migrations.AddField(
            model_name="companynotes",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
