# Generated by Django 5.0.1 on 2024-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_permisions",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
