# Generated by Django 5.0.1 on 2024-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0002_user_staff_permisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="product_permisons",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
