# Generated by Django 5.0.1 on 2024-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_user_product_permisons"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="target_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
