# Generated by Django 5.0.6 on 2024-08-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0004_user_target_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="product_permisons",
            new_name="is_electrician",
        ),
    ]
